name: PRD Pipeline

on:
  push:
    tags:
      - '*-prd'

# 
jobs:
  deploy_sit:
    name: Deploy to STG
    runs-on: ubuntu-latest
    
    environment:
      name: PRD
      url: 'http://xxxx/hello'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main