name: SIT Pipeline

on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master
  workflow_dispatch:

# 
jobs:
  deploy_sit:
    name: Deploy to SIT
    runs-on: ubuntu-latest
    
    environment:
      name: SIT
      url: 'http://xxxx/hello'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: git tag SIT
        run: echo hello git tag