name: SIT Pipeline

on:    
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


# 
jobs:
  deploy_sit:
    name: Deploy to SIT
    runs-on: ubuntu-latest
    environment:
      name: SIT
      url: 'http://xxxx/hello'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: TAG
      run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: ECHO
      run: echo $GITHUB_ENV

    # - uses: actions/github-script@v4
    #   name: make tag name
    #   env:
    #       ENV_VAR: $MY_VAR
    #   with:
    #     script: |
    #       const { ENV_VAR } = process.env
    #       console.log(`hello ${ENV_VAR}`)


    # - name: create tag
    #   run: |
    #     git tag 0.1.4
    #     git push origin --tags 0.1.4

    # - name: echo ref
    #   run: echo ${{ github.ref }}



