name: SIT Pipeline

on:    
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


# 
jobs:
  deploy_sit:
    name: Deploy to SIT
    runs-on: ubuntu-latest
    environment:
      name: SIT
      url: 'http://xxxx/hello'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: create tag
      run: |
        git tag v0.1.4
        git push origin --tags v0.1.4

    - name: echo ref
      run: echo ${{ github.ref }}



