name: SIT Pipeline

on:    
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


# 
jobs:
  deploy_sit:
    name: Deploy to SIT
    runs-on: ubuntu-latest
    environment:
      name: SIT
      url: 'http://xxxx/hello'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    
    - uses: actions/github-script@v4
      name: make tag name
      with:
        script: |
          console.log('hello')


    - name: create tag
      run: |
        git tag 0.1.4
        git push origin --tags 0.1.4

    - name: echo ref
      run: echo ${{ github.ref }}



